require_relative 'xsd_reader/shared'
require_relative 'xsd_reader/xml'
require_relative 'xsd_reader/schema'
require_relative 'xsd_reader/element'
require_relative 'xsd_reader/attribute'
require_relative 'xsd_reader/sequence'
require_relative 'xsd_reader/choice'
require_relative 'xsd_reader/complex_type'
require_relative 'xsd_reader/simple_content'
require_relative 'xsd_reader/complex_content'
require_relative 'xsd_reader/extension'
require_relative 'xsd_reader/import'
require_relative 'xsd_reader/simple_type'

